MVCHOT3/Models/DomainModels/BowlingBall.cs
using System.ComponentModel.DataAnnotations;
namespace MVCHOT3.Models
{
	public class BowlingBall
	{
		public int Id { get; set; }
		[Required(ErrorMessage = "Name is Required")]
		public string? Name { get; set; }
		[Required(ErrorMessage = "Brand is Required")]
		public string? Brand { get; set; }
		[Required(ErrorMessage = "Price is Required")]
		[Range(0, 1000, ErrorMessage = "Price must be between 0 and 1000")]
		public decimal Price { get; set; }
		public string? ImageFileName { get; set; }
		public string Slug => $"{Brand}-{Name}".ToLower().Replace(" ", "-");
	}
}

MVCHOT3/Areas/Admin/Controllers/BowlingBallController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCHOT3.Models;
namespace MVCHOT3.Areas.Admin.Controllers
{
    [Area("Admin")]
	public class BowlingBallController : Controller
	{
		private readonly ShopContext _context;

		public BowlingBallController(ShopContext context)
		{
			_context = context;
		}
		public IActionResult Index()
		{
			return View();
		}

		[Route("[area]/bowlingballs/{brand?}/{slug?}")]
		public IActionResult List(string brand = "all")
		{
			List<BowlingBall> bowlingballs;

			if (brand.Equals("all"))
			{
				bowlingballs = _context.BowlingBalls.ToList();
			}
			else
			{
				bowlingballs = _context.BowlingBalls.Where(b => b.Brand == brand).ToList();
			}
			return View(bowlingballs);
		}

		[HttpGet]
		public IActionResult Add(int? id)
		{
			if (id.HasValue)
			{
				var bowlingball = _context.BowlingBalls.Find(id.Value);
				if (bowlingball != null)
				{
					return View("AddEdit", bowlingball);
				}
			}
			return View("AddEdit", new BowlingBall());
		}

		[HttpPost]
		public IActionResult Add(BowlingBall bowlingball)
		{
			if (ModelState.IsValid)
			{
				if (bowlingball.Id == 0)
				{
					_context.BowlingBalls.Add(bowlingball);
				}
				else
				{
					_context.BowlingBalls.Update(bowlingball);
				}

				_context.SaveChanges();
				return RedirectToAction("List");
			}

			return View("AddEdit", bowlingball);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var bowlingball = _context.BowlingBalls.Find(id);
			if (bowlingball != null)
			{
				return View(bowlingball);
			}
			return RedirectToAction("List");
		}

		[HttpPost]
		public IActionResult DeleteBowlingBall(int id)
		{
			var bowlingball = _context.BowlingBalls.Find(id);
			if (bowlingball != null)
			{
				_context.BowlingBalls.Remove(bowlingball);
				_context.SaveChanges();
			}
			return RedirectToAction("List");
		}
	}
} 

MVCHOT3/Controllers/BowlingBallController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCHOT3.Models;

namespace MVCHOT3.Controllers
{
    public class BowlingBallController : Controller
	{
		private readonly ShopContext _context;

		public BowlingBallController(ShopContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		[Route("bowlingballs/{brand?}")]
		public IActionResult List(string brand = "all")
		{
			List<BowlingBall>bowlingballs;
			if (brand.Equals("all"))
			{
				bowlingballs = _context.BowlingBalls.ToList();
			}
			else
			{
				bowlingballs = _context.BowlingBalls.Where(b => b.Brand == brand).ToList();
			}
			return View(bowlingballs);
		}

		[Route("bowlingball/{id}/{slug?}")]
		public IActionResult Details(int id)
		{
			var bowlingball = _context.BowlingBalls.Find(id);
			if (bowlingball != null && bowlingball.ImageFileName != null)
			{
				bowlingball.ImageFileName = "/images/" + bowlingball.ImageFileName;
			}
			return View(bowlingball);
		}
	}
}

MVCHOT3/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MVCHOT3.Models;
using Microsoft.AspNetCore.Authorization;

namespace MVCHOT3.Controllers
{
	[Authorize]
    public class ShoppingCartController : Controller
	{
		private readonly ShopContext _context;
		private List<ShoppingCartItem> _cartItems;

		public ShoppingCartController(ShopContext context)
		{
			_context = context;
			_cartItems= new List<ShoppingCartItem>();
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult AddToCart(int id)
		{
			var bowlingBallToAdd = _context.BowlingBalls.Find(id);
			var cartItems = HttpContext.Session.Get<List<ShoppingCartItem>>("Cart") ?? new List<ShoppingCartItem>();
			var existingCartItem = cartItems.FirstOrDefault(item => item.BowlingBall.Id == id);

			if (existingCartItem != null)
			{
				existingCartItem.Quantity++;
			}
			else
			{
				cartItems.Add(new ShoppingCartItem
				{
					BowlingBall = bowlingBallToAdd,
					Quantity = 1
				});
			}

			HttpContext.Session.Set("Cart", cartItems);
			TempData["CartMessage"] = $"{bowlingBallToAdd.Brand} {bowlingBallToAdd.Name} added to cart";
			return RedirectToAction("ViewCart");
		}

		public IActionResult ViewCart()
		{
			var cartItems = HttpContext.Session.Get<List<ShoppingCartItem>>("Cart") ?? new List<ShoppingCartItem>();
			var cartViewModel = new ShoppingCartViewModel
			{
				CartItems = cartItems,
				TotalPrice = cartItems.Sum(item => item.BowlingBall.Price * item.Quantity)
			};

			ViewBag.CartMessage = TempData["CartMessage"];
			return View(cartViewModel);
		}

		public IActionResult RemoveItem(int id)
		{
			var cartItems = HttpContext.Session.Get<List<ShoppingCartItem>>("Cart") ?? new List<ShoppingCartItem>();
			var itemToRemove = cartItems.FirstOrDefault(item => item.BowlingBall.Id == id);
			TempData["CartMessage"] = $"{itemToRemove.BowlingBall.Brand} {itemToRemove.BowlingBall.Name} Removed From Cart";
			if (itemToRemove != null)
			{
				if (itemToRemove.Quantity > 1)
				{
					itemToRemove.Quantity--;
				}
				else
				{
					cartItems.Remove(itemToRemove);
				}
			}

			HttpContext.Session.Set("Cart", cartItems);
			return RedirectToAction("ViewCart");
		}

		public IActionResult PurchaseItems()
		{
			var cartItems = HttpContext.Session.Get<List<ShoppingCartItem>>("Cart") ?? new List<ShoppingCartItem>();
			foreach (var item in cartItems)
			{
				_context.Purchases.Add(new Purchase
				{
					BowlingBallId = item.BowlingBall.Id,
					Quantity = item.Quantity,
					PurchaseDate = DateTime.Now,
					Total = item.BowlingBall.Price * item.Quantity
				});
			}
			_context.SaveChanges();
			HttpContext.Session.Set("Cart", new List<ShoppingCartItem>());
			return RedirectToAction("Index", "Home");
		}
	}
} 

MVCHOT3/Views/BowlingBall/Details.cshtml
@model MVCHOT3.Models.BowlingBall
@{
	ViewBag.Title = "Bowling Ball Details";
}
<h1>Bowling Ball Details</h1>

<input type="hidden" value="@Model.Id" />
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card" style="width: 18rem;">
            <img src="@Model.ImageFileName" class="card-img-top" alt="...">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Model.Name</li>
                    <li class="list-group-item">@Model.Brand</li>
                    <li class="list-group-item">@Model.Price.ToString("C")</li>
                    <li class="list-group-item"><a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" class="btn btn-primary">Add to Cart</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div> 

MVCHOT3/Views/BowlingBall/List.cshtml
@model List<MVCHOT3.Models.BowlingBall>
@{
	ViewBag.Title = "Bowling Ball List";
}

<h1>Bowling Ball List</h1>
<div class="row">
    <div class="col-md-2">
        <ul class="list-group">
            <li class="list-group-item">
                <a asp-controller="BowlingBall" asp-action="List" asp-route-brand="motiv" class="nav-link">Motiv</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="BowlingBall" asp-action="List" asp-route-brand="roto grip" class="nav-link">Roto Grip</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="BowlingBall" asp-action="List" asp-route-brand="hammer" class="nav-link">Hammer</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="BowlingBall" asp-action="List" asp-route-brand="pyramid" class="nav-link">Pyramid</a>
            </li>
        </ul>
    </div>
    <div class="col-md-10">
        <table class="table table-info table-striped">
            <tr>
                <th>
                    Brand
                </th>
                <th>
                    Model
                </th>
                <th>
                    Price
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a asp-controller="BowlingBall" asp-action="Details" asp-route-id="@item.Id" asp-route-slug="@item.Slug">Details</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div> 